# Generated by Django 4.0.6 on 2022-08-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
